---
# file: inventory/host_vars/radarr01.yml
ansible_host: 192.168.1.28
node: pve01
vmid: 340
cores: 1
memory: 256
swap: 256
storage: local-lvm:4
mounts:
  mp0: /mnt/plex-media/plex,mp=/mnt/plex
mount_volumes: # on 9.2.0 - these fields are totally bugged, leaving this here for the time being til fix
  - id: mp0
    host_path: /mnt/plex-media/plex
    mountpoint: /mnt/plex
hwaddr: 02:00:00:00:00:1c
ip: 192.168.1.28/24
gw: 192.168.1.1
ip6: fe80::1c/11
gw6: fe80::ff:fe00:2201
features:
description: Radarr LXC - Radarr is a movie collection manager for Usenet and BitTorrent users. It can monitor multiple RSS feeds for new movies and will interface with clients and indexers to grab, sort, and rename them.
ostemplate: local:vztmpl/debian-12-standard_12.2-1_amd64.tar.zst
template_storage: local
template_content_type: vztmpl
template: debian-12-standard_12.2-1_amd64.tar.zst
notes: n/a
