---
# file: roles/kvm/tasks/main.yml
- name: Install Prometheus's node_exporter for alpine
  when: ansible_facts['os_family'] | lower == 'alpine'
  community.general.apk:
    name:
      - prometheus-node-exporter

- name: Install Prometheus's node_exporter for debian
  when: ansible_facts['os_family'] | lower == 'debian'
  ansible.builtin.apt:
    name:
      - prometheus-node-exporter
