---
# file: create.yml
- name: Create infrastructure hosts playbook
  hosts: pve
  tasks:
    - name: Create infrastructure
      ansible.builtin.include_role:
        name: proxmox_lxc_add_container
