---
# file: create.yml
- name: Create hosts playbook
  hosts: pve
  tasks:
    - name: Create lxc infrastructure
      loop: "{{ groups['lxc'] }}"
      when:
        - inventory_hostname in groups['pve']
        - inventory_hostname == hostvars[item].node
        - ('lxc' in ansible_limit) or (item in (ansible_limit | default(groups['lxc'])))
      ansible.builtin.include_role:
        name: proxmox_lxc
      vars:
        proxmox_lxc_node: "{{ hostvars[item].node }}"
        proxmox_lxc_api_host: "{{ inventory_hostname }}"
        proxmox_lxc_api_user: "{{ api_user }}"
        proxmox_lxc_api_password: "{{ api_password }}"
        proxmox_lxc_vmid: "{{ hostvars[item].vmid }}"
        proxmox_lxc_hostname: "{{ item }}"
        proxmox_lxc_cores: "{{ hostvars[item].cores }}"
        proxmox_lxc_memory: "{{ hostvars[item].memory }}"
        proxmox_lxc_swap: "{{ hostvars[item].swap }}"
        proxmox_lxc_storage: "{{ hostvars[item].storage }}"
        proxmox_lxc_mounts: "{{ hostvars[item].mounts | default(omit) }}"
        proxmox_lxc_mount_volumes: "{{ hostvars[item].mount_volumes | default(omit) }}"
        proxmox_lxc_netif_net0_name: eth0
        proxmox_lxc_netif_net0_hwaddr: "{{ hostvars[item].hwaddr }}"
        proxmox_lxc_netif_net0_ip: "{{ hostvars[item].ip }}"
        proxmox_lxc_netif_net0_gw: "{{ hostvars[item].gw }}"
        proxmox_lxc_netif_net0_ip6: "{{ hostvars[item].ip6 }}"
        proxmox_lxc_netif_net0_gw6: "{{ hostvars[item].gw6 }}"
        proxmox_lxc_netif_net0_bridge: vmbr0
        proxmox_lxc_timezone: host
        proxmox_lxc_pubkey: "{{ lookup('ansible.builtin.file', 'ssh-keys/homelab.pub') }}"
        proxmox_lxc_features: "{{ hostvars[item].features | default(omit) }}"
        proxmox_lxc_description: "{{ hostvars[item].description }}"
        proxmox_lxc_onboot: true
        proxmox_lxc_ostemplate: "{{ hostvars[item].ostemplate }}"
        proxmox_lxc_template_storage: "{{ hostvars[item].template_storage }}"
        proxmox_lxc_template_content_type: "{{ hostvars[item].template_content_type }}"
        proxmox_lxc_template: "{{ hostvars[item].template }}"

    - name: Create kvm infrastructure
      loop: "{{ groups['kvm'] }}"
      when:
        - inventory_hostname in groups['pve']
        - inventory_hostname == hostvars[item].node
        - ('kvm' in ansible_limit) or (item in (ansible_limit | default(groups['kvm'])))
      ansible.builtin.include_role:
        name: proxmox_kvm
      vars:
        proxmox_kvm_node: "{{ hostvars[item].node }}"
        proxmox_kvm_api_host: "{{ inventory_hostname }}"
        proxmox_kvm_api_user: "{{ api_user }}"
        proxmox_kvm_api_password: "{{ api_password }}"
        proxmox_kvm_vmid: "{{ hostvars[item].vmid }}"
        proxmox_kvm_name: "{{ item }}"
        proxmox_kvm_cores: "{{ hostvars[item].cores }}"
        proxmox_kvm_memory: "{{ hostvars[item].memory }}"
        proxmox_kvm_storage: "{{ hostvars[item].storage }}"
        proxmox_kvm_size: "{{ hostvars[item].size }}"
        proxmox_kvm_net_net0_hwaddr: "{{ hostvars[item].hwaddr }}"
        proxmox_kvm_ipconfig_ipconfig0_ip: "{{ hostvars[item].ip }}"
        proxmox_kvm_ipconfig_ipconfig0_gw: "{{ hostvars[item].gw }}"
        proxmox_kvm_ipconfig_ipconfig0_ip6: "{{ hostvars[item].ip6 }}"
        proxmox_kvm_ipconfig_ipconfig0_gw6: "{{ hostvars[item].gw6 }}"
        proxmox_kvm_description: "{{ hostvars[item].description }}"
        proxmox_kvm_image_remote_url: "{{ hostvars[item].kvm_image_remote_url }}"
        proxmox_kvm_image_checksum: "{{ hostvars[item].kvm_image_checksum }}"
        proxmox_kvm_sshkeys: "{{ lookup('ansible.builtin.file', 'ssh-keys/homelab.pub') }}"
        proxmox_kvm_onboot: true

- name: Specific host playbook
  hosts: all
  tasks:
    - name: Run host specific task file
      ansible.builtin.include_tasks: "tasks/{{ inventory_hostname }}.yml"
