---
# file: csv_export.yml
- name: Generate an HTML report from Jinja2 template
  hosts: all
  gather_facts: true
  vars:
    headers: ip,ip6,mac,ihostname,hostname,domain,fqdn,vrole,vrole_info,vtype,vcpu,memtotal,storage,os,notes # noqa: yaml[line-length]

    fields_values:
      - "{{ ansible_default_ipv4.address is defined | ansible.builtin.ternary(ansible_default_ipv4.address,'null') }}"
      - "{{ ansible_default_ipv6.address is defined | ansible.builtin.ternary(ansible_default_ipv6.address,'null') }}"
      - "{{ ansible_default_ipv4.macaddress is defined | ansible.builtin.ternary(ansible_default_ipv4.macaddress,'null') }}"
      - "{{ inventory_hostname is defined | ansible.builtin.ternary(inventory_hostname,'null') }}"
      - "{{ ansible_hostname is defined | ansible.builtin.ternary(ansible_hostname,'null') }}"
      - "{{ ansible_domain is defined | ansible.builtin.ternary(ansible_domain,'null') }}"
      - "{{ ansible_fqdn is defined | ansible.builtin.ternary(ansible_fqdn,'null') }}"
      - "{{ ansible_virtualization_role is defined | ansible.builtin.ternary(ansible_virtualization_role,'null') }}"
      - "{{ (ansible_virtualization_role == 'host') | ansible.builtin.ternary(ansible_virtualization_tech_host is defined | ansible.builtin.ternary(ansible_virtualization_tech_host | join(' '),'null'), ansible_virtualization_tech_guest is defined | ansible.builtin.ternary(ansible_virtualization_tech_guest | join(' '),'null')) }}" # noqa: yaml[line-length]
      - "{{ ansible_virtualization_type is defined | ansible.builtin.ternary(ansible_virtualization_type,'null') }}"
      - "{{ ansible_processor_vcpus is defined | ansible.builtin.ternary(ansible_processor_vcpus,'null') }}"
      - "{{ ansible_memory_mb.real.total is defined | ansible.builtin.ternary(ansible_memory_mb.real.total,'null') }}"
      - "{{ storage is defined | ansible.builtin.ternary(storage,'null') }}"
      - "{{ ansible_distribution is defined | ansible.builtin.ternary(ansible_distribution,'null') }}-{{ ansible_distribution_version is defined | ansible.builtin.ternary(ansible_distribution_version,'null') }}-{{ ansible_distribution_release is defined | ansible.builtin.ternary(ansible_distribution_release,'null') }}-{{ ansible_architecture is defined | ansible.builtin.ternary(ansible_architecture,'null') }}" # noqa: yaml[line-length]
      - "{{ notes is defined | ansible.builtin.ternary(notes,'null') }}"


  tasks:
    - name: Delete existing hosts_facts.csv
      ansible.builtin.file:
        path: ./reports/hosts_facts.csv
        state: absent
      delegate_to: localhost
      when: inventory_hostname == ansible_play_hosts_all[0]

    - name: Build host facts into csv line
      ansible.builtin.lineinfile:
        line: "{{ fields_values | join(',') }}"
        dest: ./reports/hosts_facts.csv
        mode: '0644'
        create: true
      throttle: 1
      delegate_to: localhost

    - name: Sort csv file content
      ansible.builtin.copy:
        content: "{{ lookup('ansible.builtin.file', './reports/hosts_facts.csv').splitlines() | sort | join('\n') }}"
        dest: ./reports/hosts_facts.csv
        mode: '0644'
      delegate_to: localhost
      when: inventory_hostname == ansible_play_hosts_all[0]

    - name: Save csv headers
      ansible.builtin.lineinfile:
        insertbefore: BOF
        line: "{{ headers }}"
        dest: ./reports/hosts_facts.csv
      delegate_to: localhost
      when: inventory_hostname == ansible_play_hosts_all[0]

    - name: Read in csv to variable
      community.general.read_csv:
        path: ./reports/hosts_facts.csv
      register: csv_file
      delegate_to: localhost
      when: inventory_hostname == ansible_play_hosts_all[0]

    - name: Create html
      ansible.builtin.copy:
        content: "{{ lookup('template', 'files/report/report.html.j2') }}"
        dest: ./reports/report.html
        mode: '0644'
      delegate_to: localhost
      when: inventory_hostname == ansible_play_hosts_all[0]

# Available easy variables and some examples
# OS

# "ansible_system": "Linux",
# "ansible_os_family": "Debian",
# "ansible_distribution": "Debian",
# "ansible_distribution_release": "bookworm",
# "ansible_distribution_version": "12.5",
# "ansible_architecture": "x86_64",
# "ansible_pkg_mgr": "apt",

# MACHINE

# "ansible_form_factor": "Desktop",
# "ansible_product_name": "NUC8i5BEK",
# "ansible_product_serial": "G6BE8480015K",
# "ansible_product_uuid": "b525e113-cf55-a733-a311-94c691a8a6ba",
# "ansible_product_version": "J72742-304",
# "ansible_machine": "x86_64",

# CPU

# "ansible_processor_cores": 4,
# "ansible_processor_count": 1,
# "ansible_processor_nproc": 8,
# "ansible_processor_threads_per_core": 2,
# "ansible_processor_vcpus": 8,

# MEMORY

# "ansible_memfree_mb": 13178,
# "ansible_memory_mb": {
#     "nocache": {
#         "free": 14443,
#         "used": 1420
#     },
#     "real": {
#         "free": 13178,
#         "total": 15863,
#         "used": 2685
#     },
#     "swap": {
#         "cached": 0,
#         "free": 8191,
#         "total": 8191,
#         "used": 0
#     }
# },
# "ansible_memtotal_mb": 7840,
# "ansible_swapfree_mb": 8191,
# "ansible_swaptotal_mb": 8191,

# DISK

# total disk size for docker
# ansible_devices.vda.partitions.vda1.size
# it's not consistent for now

# NETWORKING

# "ansible_domain": "local",
# "ansible_fqdn": "pve01.local",
# "ansible_hostname": "pve01",
# "ansible_nodename": "pve01",

# "ansible_default_ipv4": {
#     "address": "192.168.1.8",
#     "gateway": "192.168.1.1",
#     "macaddress": "94:c6:91:a8:a6:ba",
#     "mtu": 1500,
#     "netmask": "255.255.255.0",
#     "network": "192.168.1.0",
#     "prefix": "24",
#     "type": "bridge"
# },
# "ansible_default_ipv6": {
#     "address": "2001:818:db61:6400:0:ff:fe00:3",
#     "gateway": "fe80::46d4:53ff:feb4:dcd7",
#     "macaddress": "02:00:00:00:00:03",
#     "mtu": 1500,
#     "prefix": "64",
# },
# "ansible_dns": {
#     "nameservers": [
#         "8.8.8.8"
#     ],
#     "search": [
#         "local"
#     ]
# },

# MISC

# "ansible_date_time": {
#     "iso8601": "2024-06-30T18:20:42Z",
#     "tz": "WEST",
# },

# "ansible_virtualization_role": "host",
# "ansible_virtualization_tech_guest": [],
# "ansible_virtualization_tech_host": [
#     "kvm"
# ],
# "ansible_virtualization_type": "kvm",
