---
# file: edit.yml
- name: Modify hosts playbook
  hosts: pve
  vars_prompt:
    - name: prompt_confirmation
      prompt: "This will modify all (non-pve) hosts on the play batch ({{ ansible_play_batch | join(',') }}), are you sure (yN)?"
      private: false
  tasks:
    - name: Run per vmid
      when: prompt_confirmation | lower == 'y'
      block:

        - name: Edit lxc infrastructure
          loop: "{{ groups['lxc'] }}"
          when: (hostvars[item].node == ansible_hostname) and (item in (ansible_limit | default(groups['lxc'])))
          ansible.builtin.include_role:
            name: proxmox_lxc_edit_container
          vars:
            proxmox_lxc_edit_container_node: "{{ hostvars[item].node }}"
            proxmox_lxc_edit_container_api_host: "{{ inventory_hostname }}"
            proxmox_lxc_edit_container_api_user: "{{ api_user }}"
            proxmox_lxc_edit_container_api_password: "{{ api_password }}"
            proxmox_lxc_edit_container_vmid: "{{ hostvars[item].vmid }}"
            proxmox_lxc_edit_container_hostname: "{{ item }}"
            proxmox_lxc_edit_container_cores: "{{ hostvars[item].cores }}"
            proxmox_lxc_edit_container_memory: "{{ hostvars[item].memory }}"
            proxmox_lxc_edit_container_swap: "{{ hostvars[item].swap }}"
            proxmox_lxc_edit_container_storage: "{{ hostvars[item].storage }}"
            proxmox_lxc_edit_container_netif_net0_name: eth0
            proxmox_lxc_edit_container_netif_net0_hwaddr: "{{ hostvars[item].hwaddr }}"
            proxmox_lxc_edit_container_netif_net0_ip: "{{ hostvars[item].ip }}"
            proxmox_lxc_edit_container_netif_net0_gw: "{{ hostvars[item].gw }}"
            proxmox_lxc_edit_container_netif_net0_ip6: "{{ hostvars[item].ip6 }}"
            proxmox_lxc_edit_container_netif_net0_gw6: "{{ hostvars[item].gw6 }}"
            proxmox_lxc_edit_container_netif_net0_bridge: vmbr0
            proxmox_lxc_edit_container_pubkey: "{{ lookup('ansible.builtin.file', 'ssh-keys/homelab.pub') }}"
            proxmox_lxc_edit_container_timezone: host
            proxmox_lxc_edit_container_description: "{{ hostvars[item].description }}"
            proxmox_lxc_edit_container_onboot: true

        - name: Edit kvm infrastructure
          loop: "{{ groups['kvm'] }}"
          when: (hostvars[item].node == ansible_hostname) and (item in (ansible_limit | default(groups['kvm'])))
          ansible.builtin.include_role:
            name: proxmox_kvm_edit_container
          vars:
            proxmox_kvm_edit_container_api_host: "{{ inventory_hostname }}"
            proxmox_kvm_edit_container_api_user: "{{ api_user }}"
            proxmox_kvm_edit_container_api_password: "{{ api_password }}"
            proxmox_kvm_edit_container_vmid: "{{ hostvars[item].vmid }}"
            # TODO
