---
# file: main.yml
- name: Nuke hosts playbook
  hosts: all
  vars_prompt:
    - name: prompt_confirmation
      prompt: "This will nuke all (non-pve) hosts on the play batch ({{ ansible_play_batch | join(',') }}), are you sure (yN)?"
      private: false
  tasks:
    - name: Run per vmid
      when: prompt_confirmation | lower == 'y'
      block:
        - name: Remove lxc infrastructure
          loop: "{{ groups['lxc'] }}"
          when:
            - inventory_hostname in groups['pve']
            - (inventory_hostname == hostvars[item].node) and (item in (ansible_limit | default(groups['lxc'])))
          ansible.builtin.include_role:
            name: proxmox_lxc_rm_container
          vars:
            proxmox_lxc_rm_container_api_host: "{{ inventory_hostname }}"
            proxmox_lxc_rm_container_api_user: "{{ api_user }}"
            proxmox_lxc_rm_container_api_password: "{{ api_password }}"
            proxmox_lxc_rm_container_vmid: "{{ hostvars[item].vmid }}"
        - name: Remove kvm infrastructure
          loop: "{{ groups['kvm'] }}"
          when:
            - inventory_hostname in groups['pve']
            - (inventory_hostname == hostvars[item].node) and (item in (ansible_limit | default(groups['kvm'])))
          ansible.builtin.include_role:
            name: proxmox_kvm_rm_container
          vars:
            proxmox_kvm_rm_container_api_host: "{{ inventory_hostname }}"
            proxmox_kvm_rm_container_api_user: "{{ api_user }}"
            proxmox_kvm_rm_container_api_password: "{{ api_password }}"
            proxmox_kvm_rm_container_vmid: "{{ hostvars[item].vmid }}"
