---
# file: pihole01.yml
- name: Running pihole01.yml playbook
  hosts: pihole01
  tasks:
    - name: Check pihole installation
      ansible.builtin.command: which pihole
      changed_when: false
      failed_when: pihole_installed.rc not in [0, 1]
      register: pihole_installed

    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        upgrade: true
        update_cache: true
        cache_valid_time: 3600 # One hour
      when: pihole_installed.rc not in [0]

    - name: Ensure curl is present
      ansible.builtin.apt:
        name: curl
        state: present
      when: pihole_installed.rc not in [0]

    - name: Create /etc/pihole if it does not exist
      ansible.builtin.file:
        path: /etc/pihole
        state: directory
        mode: '0755'
      when: pihole_installed.rc not in [0]

    - name: Copy setupVars.conf with owner and permissions
      ansible.builtin.copy:
        src: files/pihole01/setupVars.conf
        dest: /etc/pihole/setupVars.conf
        owner: root
        group: root
        mode: '0644'
      when: pihole_installed.rc not in [0]

    - name: Run script if pi-hole not installed
      ansible.builtin.shell: curl -L https://install.pi-hole.net | bash /dev/stdin --unattended
      when: pihole_installed.rc not in [0]
      tags:
        - skip_ansible_lint

    - name: Copy 99-edns.conf with owner and permissions
      ansible.builtin.copy:
        src: files/pihole01/99-edns.conf
        dest: /etc/dnsmasq.d/99-edns.conf
        owner: root
        group: root
        mode: '0644'
