---
# file: pve01.yml
- name: Running pve01.yml playbook
  hosts: pve
  roles:
    - proxmox
  tasks:
    - name: Make sure base system container template is present
      community.general.proxmox_template:
        node: "{{ ansible_hostname }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        api_host: "{{ inventory_hostname }}"
        storage: local
        content_type: vztmpl
        template: debian-12-standard_12.2-1_amd64.tar.zst
        state: present

    - name: Create lxc containers
      community.general.proxmox:
        node: "{{ ansible_hostname }}"
        api_host: "{{ inventory_hostname }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        ostemplate: 'local:vztmpl/debian-12-standard_12.2-1_amd64.tar.zst'
        vmid: "{{ hostvars[item].vmid }}"
        hostname: "{{ item }}"
        description: "{{ hostvars[item].description }}"
        cores: "{{ hostvars[item].cores }}"
        memory: "{{ hostvars[item].memory }}"
        storage: "{{ hostvars[item].storage }}" # Hidden required field
        netif: '{"net0":"name=eth0,hwaddr={{ hostvars[item].hwaddr }},gw={{ hostvars[item].gw }},ip={{ hostvars[item].ip }},ip6=dhcp,bridge=vmbr0"}'
        pubkey: "{{ lookup('ansible.builtin.file', 'ssh-keys/homelab.pub') }}"
        timezone: host
        onboot: true
        state: present
      loop: "{{ groups['lxc'] }}"

    - name: Start containers
      community.general.proxmox:
        api_host: "{{ inventory_hostname }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        vmid: "{{ hostvars[item].vmid }}"
        state: started
      loop: "{{ groups['lxc'] }}"
