---
# file: rebuild.yml
- name: Rebuild hosts playbook
  hosts: pve
  vars_prompt:
    - name: prompt_confirmation
      prompt: "This will nuke and create all (non-pve) hosts on the play batch ({{ ansible_play_batch | join(',') }}), are you sure (yN)?"
      private: false
  tasks:
    - name: Run per vmid
      when: prompt_confirmation | lower == 'y'
      block:

        - name: Remove lxc infrastructure
          loop: "{{ groups['lxc'] }}"
          when: (hostvars[item].node == ansible_hostname) and (item in (ansible_limit | default(groups['lxc'])))
          ansible.builtin.include_role:
            name: proxmox_lxc_rm_container
          vars:
            proxmox_lxc_rm_container_api_host: "{{ inventory_hostname }}"
            proxmox_lxc_rm_container_api_user: "{{ api_user }}"
            proxmox_lxc_rm_container_api_password: "{{ api_password }}"
            proxmox_lxc_rm_container_vmid: "{{ hostvars[item].vmid }}"

        - name: Create lxc infrastructure
          loop: "{{ groups['lxc'] }}"
          when: (hostvars[item].node == ansible_hostname) and (item in (ansible_limit | default(groups['lxc'])))
          ansible.builtin.include_role:
            name: proxmox_lxc_add_container
          vars:
            proxmox_lxc_add_container_node: "{{ hostvars[item].node }}"
            proxmox_lxc_add_container_api_host: "{{ inventory_hostname }}"
            proxmox_lxc_add_container_api_user: "{{ api_user }}"
            proxmox_lxc_add_container_api_password: "{{ api_password }}"
            proxmox_lxc_add_container_vmid: "{{ hostvars[item].vmid }}"
            proxmox_lxc_add_container_hostname: "{{ item }}"
            proxmox_lxc_add_container_cores: "{{ hostvars[item].cores }}"
            proxmox_lxc_add_container_memory: "{{ hostvars[item].memory }}"
            proxmox_lxc_add_container_swap: "{{ hostvars[item].swap }}"
            proxmox_lxc_add_container_storage: "{{ hostvars[item].storage }}"
            proxmox_lxc_add_container_netif_net0_name: eth0
            proxmox_lxc_add_container_netif_net0_hwaddr: "{{ hostvars[item].hwaddr }}"
            proxmox_lxc_add_container_netif_net0_ip: "{{ hostvars[item].ip }}"
            proxmox_lxc_add_container_netif_net0_gw: "{{ hostvars[item].gw }}"
            proxmox_lxc_add_container_netif_net0_ip6: "{{ hostvars[item].ip6 }}"
            proxmox_lxc_add_container_netif_net0_gw6: "{{ hostvars[item].gw6 }}"
            proxmox_lxc_add_container_netif_net0_bridge: vmbr0
            proxmox_lxc_add_container_pubkey: "{{ lookup('ansible.builtin.file', 'ssh-keys/homelab.pub') }}"
            proxmox_lxc_add_container_ostemplate: "{{ hostvars[item].ostemplate }}"
            proxmox_lxc_add_container_timezone: host
            proxmox_lxc_add_container_description: "{{ hostvars[item].description }}"
            proxmox_lxc_add_container_onboot: true
            proxmox_lxc_add_container_template_storage: "{{ hostvars[item].template_storage }}"
            proxmox_lxc_add_container_template_content_type: "{{ hostvars[item].template_content_type }}"
            proxmox_lxc_add_container_template: "{{ hostvars[item].template }}"

        - name: Remove kvm infrastructure
          loop: "{{ groups['kvm'] }}"
          when: (hostvars[item].node == ansible_hostname) and (item in (ansible_limit | default(groups['kvm'])))
          ansible.builtin.include_role:
            name: proxmox_kvm_rm_container
          vars:
            proxmox_kvm_rm_container_api_host: "{{ inventory_hostname }}"
            proxmox_kvm_rm_container_api_user: "{{ api_user }}"
            proxmox_kvm_rm_container_api_password: "{{ api_password }}"
            proxmox_kvm_rm_container_vmid: "{{ hostvars[item].vmid }}"

        - name: Create kvm infrastructure
          loop: "{{ groups['kvm'] }}"
          when: (hostvars[item].node == ansible_hostname) and (item in (ansible_limit | default(groups['kvm'])))
          ansible.builtin.include_role:
            name: proxmox_kvm_add_container
          vars:
            proxmox_kvm_add_container_node: "{{ hostvars[item].node }}"
            proxmox_kvm_add_container_api_host: "{{ inventory_hostname }}"
            proxmox_kvm_add_container_api_user: "{{ api_user }}"
            proxmox_kvm_add_container_api_password: "{{ api_password }}"
            proxmox_kvm_add_container_vmid: "{{ hostvars[item].vmid }}"
            proxmox_kvm_add_container_hostname: "{{ item }}"
            proxmox_kvm_add_container_cores: "{{ hostvars[item].cores }}"
            proxmox_kvm_add_container_memory: "{{ hostvars[item].memory }}"
            proxmox_kvm_add_container_swap: "{{ hostvars[item].swap }}"
            proxmox_kvm_add_container_storage: "{{ hostvars[item].storage }}"
            proxmox_kvm_add_container_netif_net0_name: eth0
            proxmox_kvm_add_container_netif_net0_hwaddr: "{{ hostvars[item].hwaddr }}"
            proxmox_kvm_add_container_netif_net0_ip: "{{ hostvars[item].ip }}"
            proxmox_kvm_add_container_netif_net0_gw: "{{ hostvars[item].gw }}"
            proxmox_kvm_add_container_netif_net0_ip6: "{{ hostvars[item].ip6 }}"
            proxmox_kvm_add_container_netif_net0_gw6: "{{ hostvars[item].gw6 }}"
            proxmox_kvm_add_container_netif_net0_bridge: vmbr0
            proxmox_kvm_add_container_pubkey: "{{ lookup('ansible.builtin.file', 'ssh-keys/homelab.pub') }}"
            proxmox_kvm_add_container_timezone: host
            proxmox_kvm_add_container_description: "{{ hostvars[item].description }}"
            proxmox_kvm_add_container_onboot: true
