---
# file: test.yml
- name: Test playbook
  hosts: pve
  tasks:
    - name: Testing debug
      ansible.builtin.debug:
        msg: "{{ ansible_hostname }}"
      when: (hostvars[item].node == ansible_hostname) and (item in (ansible_limit | default(groups['lxc'])))
      loop: "{{ groups['lxc'] }}"
