---
# file: tasks/auth01.yml
- name: Running auth01.yml playbook
  when: ansible_hostname == 'auth01'
  block:
    - name: Import role lxc
      ansible.builtin.include_role:
        name: lxc

    - name: Authelia - Download gpg key
      ansible.builtin.get_url:
        url: https://apt.authelia.com/organization/signing.asc
        dest: /usr/share/keyrings/apt.authelia.com.asc
        mode: 0644
        force: true

    - name: Authelia - Add apt source
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/apt.authelia.com.asc] https://apt.authelia.com/stable/debian/debian/ all main

    - name: Install required system packages
      ansible.builtin.apt:
        pkg:
          - authelia=4.38.*
          - rsyslog
        cache_valid_time: 3600

    - name: Copy configuration.yml file
      ansible.builtin.template:
        src: templates/authelia/configuration.yml.j2
        dest: /etc/authelia/configuration.yml
        mode: 0700
      vars:
        authelia_secret: "{{ vault_authelia_secret }}"
        authelia_jwt_secret: "{{ vault_authelia_jwt_secret }}"
        authelia_encryption_key: "{{ vault_authelia_encryption_key }}"
      register: _authelia_copy_configuration_yml

    - name: Update permissions for /config with +x
      ansible.builtin.file:
        path: /config
        state: directory
        mode: 0700

    - name: Check if /config/users_database.yml exists
      ansible.builtin.stat:
        path: /config/users_database.yml
      register:
        _authelia_users_database_stat

    - name: Touch yaml authelia users database
      when: not _authelia_users_database_stat.stat.exists
      ansible.builtin.file:
        path: /config/users_database.yml
        state: touch
        mode: 0600

    - name: Copy users_database.yml file
      ansible.builtin.template:
        src: templates/authelia/users_database.yml.j2
        dest: /config/users_database.yml
        mode: 0600
      vars:
        authelia_default_username: "{{ vault_authelia_default_username }}"
        authelia_default_displayname: "{{ vault_authelia_default_displayname }}"
        authelia_default_password: "{{ vault_authelia_default_password }}"
        authelia_default_email: "{{ vault_authelia_default_email }}"
      register: _authelia_copy_users_database_yml

    - name: Restart authelia service
      when: _authelia_copy_configuration_yml.changed or _authelia_copy_users_database_yml.changed
      ansible.builtin.systemd_service:
        name: authelia
        enabled: true
        state: restarted

    - name: Copy 48-authelia.conf
      ansible.builtin.copy:
        src: files/authelia/rsyslog.d/48-authelia.conf
        dest: /etc/rsyslog.d/48-authelia.conf
        mode: 0644
      register: copy_48_authelial_conf

    - name: Restart rsyslog service
      when: copy_48_authelial_conf.changed
      ansible.builtin.systemd_service:
        name: rsyslog
        enabled: true
        state: restarted

    - name: Copy authelia
      ansible.builtin.copy:
        src: files/authelia/logrotate.d/authelia
        dest: /etc/logrotate.d/authelia
        mode: 0644
      register: copy_logrotate_d_authelia

    - name: Restart logrotate service
      when: copy_logrotate_d_authelia.changed
      ansible.builtin.systemd_service:
        name: logrotate
        state: restarted
