---
# file: tasks/haproxy01.yml
- name: Running haproxy01.yml playbook
  when: ansible_hostname == 'haproxy01'
  block:
    - name: Import role lxc
      ansible.builtin.include_role:
        name: lxc

    - name: HAProxy - Download gpg key
      ansible.builtin.get_url:
        url: https://haproxy.debian.net/bernat.debian.org.gpg
        dest: /usr/share/keyrings/haproxy.debian.net.asc
        mode: 0644
        force: true

    - name: HAProxy - Add apt source
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64 signed-by=/usr/share/keyrings/haproxy.debian.net.asc] http://haproxy.debian.net bookworm-backports-3.0 main
        state: present

    - name: Install required system packages
      ansible.builtin.apt:
        pkg:
          - git
          - lua-json
          - rsyslog-gnutls
          - certbot
          - python3-certbot-dns-cloudflare
          - haproxy=3.0.*
        update_cache: true

    # certbot configuration

    - name: Add certbot config to /etc/letsencrypt/cli.ini
      ansible.builtin.blockinfile:
        path: /etc/letsencrypt/cli.ini
        block: |
          # Use a 4096 bit RSA key instead of 2048
          rsa-key-size = 4096
          # Uncomment and update to register with the specified e-mail address
          email = adelinofaria@me.com
          # Or instead, perform the registration without email
          #register-unsafely-without-email=true
          # Uncomment and update to generate certificates for the specified domains.
          domains=adelinofaria.me,*.adelinofaria.me
          # Auto accept TOS
          agree-tos=true
          # Challenge config
          preferred-challenges=dns
          authenticator=dns-cloudflare
          dns-cloudflare-credentials=/root/.secrets/certbot/cloudflare.ini

    - name: Create .secrets/certbot directory
      ansible.builtin.file:
        path: /root/.secrets/certbot
        state: directory
        mode: 0600
        recurse: yes

    - name: Copy cloudflare.ini file
      ansible.builtin.template:
        src: templates/haproxy/cloudflare.ini.j2
        dest: /root/.secrets/certbot/cloudflare.ini
        mode: 0600
      vars:
        dns_cloudflare_api_token: "{{ vault_cf_api_token }}"

    - name: Copy renewal-hooks-pre
      ansible.builtin.copy:
        src: files/haproxy/renewal-hooks/pre/10-haproxy
        dest: /etc/letsencrypt/renewal-hooks/pre/10-haproxy
        mode: 0700

    - name: Copy renewal-hooks-post
      ansible.builtin.copy:
        src: files/haproxy/renewal-hooks/post/10-haproxy
        dest: /etc/letsencrypt/renewal-hooks/post/10-haproxy
        mode: 0700

    - name: Copy renewal-hooks-deploy
      ansible.builtin.copy:
        src: files/haproxy/renewal-hooks/deploy/10-haproxy
        dest: /etc/letsencrypt/renewal-hooks/deploy/10-haproxy
        mode: 0700

    # Run certbot

    - name: Run certbot
      ansible.builtin.command: certbot certonly -n
      register: _cmd_certbot_certonly
      changed_when: _cmd_certbot_certonly.stdout_lines[0] != "Certificate not yet due for renewal"

    # Import certificates to haproxy

    - name: Create /etc/haproxy/certs folder
      ansible.builtin.file:
        path: /etc/haproxy/certs
        state: directory
        mode: 0600

    - name: Is cert installed
      ansible.builtin.stat:
        path: /etc/haproxy/certs/adelinofaria.me.pem
      register: cert_file

    - name: Install certificate
      when: not cert_file.stat.exists
      block:
        - name: Run renewal-hooks/deploy/*
          ansible.builtin.command: run-parts /etc/letsencrypt/renewal-hooks/deploy/
          environment:
            RENEWED_LINEAGE: /etc/letsencrypt/live/adelinofaria.me
            RENEWED_DOMAINS: adelinofaria.me *.adelinofaria.me

    - name: Copy haproxy.cfg
      ansible.builtin.copy:
        src: files/haproxy/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        mode: 0644
      register: copy_haproxy_cfg

    - name: Create /usr/share/haproxy directory
      ansible.builtin.file:
        path: /usr/share/haproxy
        state: directory
        mode: 0755

    - name: Clone haproxy-auth-request into /usr/share/haproxy
      ansible.builtin.git:
        repo: https://github.com/TimWolla/haproxy-auth-request.git
        dest: /usr/share/haproxy/haproxy-auth-request
        accept_newhostkey: true
        single_branch: true
        version: main

    - name: Restart haproxy service
      when: (not cert_file.stat.exists) or copy_haproxy_cfg.changed
      ansible.builtin.systemd_service:
        name: haproxy
        enabled: true
        state: restarted

    - name: Update /etc/rsyslog.d/49-haproxy.conf to forward logs to logs01:514 using TCP
      ansible.builtin.blockinfile:
        path: /etc/rsyslog.d/49-haproxy.conf
        insertafter: '  /var/log/haproxy.log'
        block: "  *.* @@192.168.1.16"
      register: rsyslog_49_haproxy_conf

    - name: Restart rsyslog service
      when: rsyslog_49_haproxy_conf.changed
      ansible.builtin.systemd_service:
        name: rsyslog
        state: restarted

# install fail2ban?


# Graylog Grok pattern for HAProxy

# HAPROXY	%{HAPROXYBASE}( %{HAPROXYMID})?( %{HAPROXYHTTPSUFFIX})?
# HAPROXYBASE	%{SYSLOGHOST:syslog_server} %{SYSLOGPROG:syslog_program}: %{IP:client_ip}:%{INT:client_port} \[%{HAPROXYDATE:accept_date}\] %{NOTSPACE:frontend_name}( %{NOTSPACE:backend_name}/%{NOTSPACE:server_name})?
# HAPROXYMID	%{HAPROXYSTATTCP}?%{HAPROXYSTATHTTP}? %{INT:actconn}/%{INT:feconn}/%{INT:beconn}/%{INT:srvconn}/%{NOTSPACE:retries} %{INT:srv_queue}/%{INT:backend_queue}
# HAPROXYHTTPSUFFIX	(\{%{HAPROXYCAPTUREDREQUESTHEADERS}\})?( )?(\{%{HAPROXYCAPTUREDRESPONSEHEADERS}\})?( )?"%{HTTP_REQUEST:http_request}"
# HAPROXYSTATHTTP	%{INT:time_request}/%{INT:time_queue}/%{INT:time_backend_connect}/%{INT:time_backend_response}/%{NOTSPACE:time_duration} %{INT:http_status_code} %{NOTSPACE:bytes_read} %{DATA:captured_request_cookie} %{DATA:captured_response_cookie} %{NOTSPACE:termination_state}
# HAPROXYSTATTCP	%{INT:time_queue}/%{INT:time_backend_connect}/%{NOTSPACE:time_duration} %{NOTSPACE:bytes_read} %{NOTSPACE:termination_state}
# HAPROXYDATE	%{MONTHDAY:haproxy_monthday}/%{MONTH:haproxy_month}/%{YEAR:haproxy_year}:%{HAPROXYTIME:haproxy_time}.%{INT:haproxy_milliseconds}
# HAPROXYTIME	(?!<[0-9])%{HOUR:haproxy_hour}:%{MINUTE:haproxy_minute}(?::%{SECOND:haproxy_second})(?![0-9])
# HAPROXYCAPTUREDREQUESTHEADERS	%{DATA:captured_request_headers}
# HAPROXYCAPTUREDRESPONSEHEADERS	%{DATA:captured_response_headers}
# HTTP_REQUEST	%{WORD:http_method} %{HTTP_URI:http_uri}( HTTP/%{NUMBER:http_version})?
# HTTP_URI	(?:%{URIPROTO}://)?(?:%{USER}(?::[^@]*)?@)?(?:%{URIHOST})?(?:%{URIPATHPARAM})?
