---
# file: tasks/homeassistant01.yml
- name: Running homeassistant01.yml playbook
  when: ansible_hostname == 'homeassistant01'
  block:
    # - name: Import role kvm
    #   ansible.builtin.include_role:
    #     name: kvm

    - name: Debug 1
      ansible.builtin.debug:
        msg:
          #- "{{ ansible_facts }}"
          - "{{ ansible_hostname }}"
          - "{{ ansible_facts['os_family'] | lower }}"

# Make sure after succesful ssh connection, to install python3
# apk update && apk add python3
