---
# file: tasks/homeassistant01.yml
# - name: Running homeassistant01.yml playbook
#   when: ansible_hostname == 'homeassistant01'
#   block:
#     - name: Import role lxc
#       ansible.builtin.include_role:
#         name: lxc

#     - name: Install dependencies
#       ansible.builtin.apt:
#         name:
#           - gpg
#           - apparmor
#           - bluez
#           - cifs-utils
#           - curl
#           - dbus
#           - jq
#           - libglib2.0-bin
#           - lsb-release
#           - network-manager
#           - nfs-common
#           - systemd-journal-remote
#     #       - systemd-resolved
#           - udisks2
#           - wget
#         update_cache: true

#     - name: Add Docker GPG apt Key
#       ansible.builtin.apt_key:
#         url: https://download.docker.com/linux/debian/gpg
#         state: present

#     - name: Add Docker Repository
#       ansible.builtin.apt_repository:
#         repo: deb https://download.docker.com/linux/debian bookworm stable
#         state: present

#     - name: Update apt and install docker-ce and docker-compose-plugin
#       ansible.builtin.apt:
#         name:
#           - docker-ce
#           - docker-compose-plugin
#           - python3-docker
#         update_cache: true

#     - name: Check if os-agent is running
#       ansible.builtin.command: gdbus introspect --system --dest io.hass.os --object-path /io/hass/os
#       register: _cmd_os_agent_output
#       changed_when: false
#       failed_when: false

#     - name: Install os-agent block
#       when: _cmd_os_agent_output.rc not in [0]
#       block:
#         - name: Download latest os-agent deb package, into install
#           ansible.builtin.shell: 'curl -s https://api.github.com/repos/home-assistant/os-agent/releases/latest | grep "browser_download_url.*_linux_x86_64.deb" | cut -d : -f 2,3 | tr -d \" | wget -O os-agent_linux_x86_64.deb -qi - && dpkg -i os-agent_linux_x86_64.deb && rm os-agent_linux_x86_64.deb'
#           register: cmd_output

#         - name: DEBUG os-agent
#           ansible.builtin.debug:
#             msg: "{{ cmd_output }}"

#     - name: Download latest supervised deb package, into install
#       ansible.builtin.shell: 'wget -O homeassistant-supervised.deb https://github.com/home-assistant/supervised-installer/releases/latest/download/homeassistant-supervised.deb && dpkg -i homeassistant-supervised.deb && rm homeassistant-supervised.deb'
#       register: cmd_output2

#     - name: DEBUG
#       ansible.builtin.debug:
#         msg: "{{ cmd_output2 }}"

#     # https://github.com/home-assistant/os-agent/releases/latest/download/os-agent_1.6.0_linux_x86_64.deb
