---
# file: tasks/plex01.yml
- name: Running plex01.yml playbook
  when: ansible_hostname == 'plex01'
  block:
    - name: Import role lxc
      ansible.builtin.include_role:
        name: lxc

    - name: Install required system packages
      ansible.builtin.apt:
        pkg:
          - curl
          - gnupg
        update_cache: true

    - name: Add Plex GPG apt Key
      ansible.builtin.apt_key:
        url: https://downloads.plex.tv/plex-keys/PlexSign.key
        state: present

    - name: Add Plex Repository
      ansible.builtin.apt_repository:
        repo: deb https://downloads.plex.tv/repo/deb public main
        state: present

    - name: Update apt and install plexmediaserver
      ansible.builtin.apt:
        name:
          - plexmediaserver
        update_cache: true
      notify: Reboot lxc

# https://www.geekbitzone.com/posts/2022/proxmox/plex-lxc/install-plex-in-proxmox-lxc/
# https://www.reddit.com/r/synology/comments/xz3fka/plex_can_transcode_directly_to_available_memory/
# https://www.reddit.com/r/synology/comments/xz3fka/plex_can_transcode_directly_to_available_memory/
