---
# file: tasks/prowlarr01.yml
- name: Running prowlarr01.yml playbook
  when: ansible_hostname == 'prowlarr01'
  block:
    - name: Prowlarr - Import role lxc
      ansible.builtin.include_role:
        name: lxc

    - name: Prowlarr - Install required system packages
      ansible.builtin.apt:
        pkg:
          - curl
          - sqlite3
        cache_valid_time: 3600

    - name: Prowlarr - Create /var/lib/prowlarr
      ansible.builtin.file:
        path: /var/lib/prowlarr
        state: directory
        mode: 0755

    - name: Prowlarr - Download package
      ansible.builtin.get_url:
        url: http://prowlarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64
        dest: /tmp
        mode: 0755
      register: _prowlarr_download_package

    - name: Prowlarr - Extract package
      ansible.builtin.unarchive:
        src: "{{ _prowlarr_download_package.dest }}"
        dest: /tmp
        remote_src: true

    - name: Prowlarr - Recursively remove directory /opt/Prowlarr
      ansible.builtin.file:
        path: /opt/Prowlarr
        state: absent

    - name: Prowlarr - Copy package from /tmp to /opt
      ansible.builtin.copy:
        src: /tmp/Prowlarr
        dest: /opt
        mode: 0755
        remote_src: yes

    - name: Prowlarr - Remove /tmp files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ _prowlarr_download_package.dest }}"
        - /tmp/Prowlarr

    - name: Prowlarr - Touch update_required flag file
      ansible.builtin.file:
        path: /var/lib/prowlarr/update_required
        state: touch
        mode: 0755

    - name: Prowlarr - Update service file
      ansible.builtin.copy:
        dest: /etc/systemd/system/prowlarr.service
        content: |
          [Unit]
          Description=Prowlarr Daemon
          After=syslog.target network.target
          [Service]
          User=0
          Group=0
          Type=simple
          ExecStart=/opt/Prowlarr/Prowlarr -nobrowser -data=/var/lib/prowlarr
          TimeoutStopSec=20
          KillMode=process
          Restart=on-failure
          [Install]
          WantedBy=multi-user.target

    - name: Prowlarr - Restart service
      ansible.builtin.systemd_service:
        name: prowlarr
        enabled: true
        state: restarted
        daemon_reload: true

    - name: Prowlarr - Service is up
      ansible.builtin.debug:
        msg:
          - "Browse to http://{{ ansible_host }}:9696 for the Prowlarr GUI"
