---
# file: tasks/pve01.yml
- name: Running pve01.yml playbook
  when: ansible_hostname == 'pve01'
  block:
    - name: Install Prometheus's node_exporter
      ansible.builtin.apt:
        name:
          - prometheus-node-exporter
        update_cache: true
