---
# file: tasks/sonarr01.yml
- name: Running sonarr01.yml playbook
  when: ansible_hostname == 'sonarr01'
  block:
    - name: Sonarr - Import role lxc
      ansible.builtin.include_role:
        name: lxc

    - name: Sonarr - Install required system packages
      ansible.builtin.apt:
        pkg:
          - curl
          - sqlite3
        cache_valid_time: 3600

    - name: Sonarr - Create /var/lib/sonarr
      ansible.builtin.file:
        path: /var/lib/sonarr
        state: directory
        mode: 0755

    - name: Sonarr - Download package
      ansible.builtin.get_url:
        url: https://services.sonarr.tv/v1/download/main/latest?version=4&os=linux&arch=x64
        dest: /tmp
        mode: 0755
      register: _sonarr_download_package

    - name: Sonarr - Extract package
      ansible.builtin.unarchive:
        src: "{{ _sonarr_download_package.dest }}"
        dest: /tmp
        remote_src: true

    - name: Sonarr - Recursively remove directory /opt/Sonarr
      ansible.builtin.file:
        path: /opt/Sonarr
        state: absent

    - name: Sonarr - Copy package from /tmp to /opt
      ansible.builtin.copy:
        src: /tmp/Sonarr
        dest: /opt
        mode: 0755
        remote_src: yes

    - name: Sonarr - Remove /tmp files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ _sonarr_download_package.dest }}"
        - /tmp/Sonarr

    - name: Sonarr - Touch update_required flag file
      ansible.builtin.file:
        path: /var/lib/sonarr/update_required
        state: touch
        mode: 0775

    - name: Sonarr - Update service file
      ansible.builtin.copy:
        dest: /etc/systemd/system/sonarr.service
        content: |
          [Unit]
          Description=Sonarr Daemon
          After=syslog.target network.target
          [Service]
          User=0
          Group=0
          UMask=0002
          Type=simple
          ExecStart=/opt/Sonarr/Sonarr -nobrowser -data=/var/lib/sonarr
          TimeoutStopSec=20
          KillMode=process
          Restart=on-failure
          [Install]
          WantedBy=multi-user.target

    - name: Sonarr - Restart service
      ansible.builtin.systemd_service:
        name: sonarr
        enabled: true
        state: restarted
        daemon_reload: true

    - name: Sonarr - Service is up
      ansible.builtin.debug:
        msg:
          - "Browse to http://{{ ansible_host }}:8989 for the Sonarr GUI"
