---
# file: tasks/unbound01.yml
- name: Running unbound01.yml playbook
  when: ansible_hostname == 'unbound01'
  block:
    - name: Import role
      ansible.builtin.include_role:
        name: lxc

    # Install dependencies

    - name: Ensure unbound is present
      ansible.builtin.apt:
        name: unbound
        state: present

    # Config files

    - name: Download root.hints
      ansible.builtin.get_url:
        url: https://www.internic.net/domain/named.root
        dest: /var/lib/unbound/root.hints
        mode: '0644'
      notify: Restart unbound
      register: roothints_file

    - name: Copy unbound01.conf with owner and permissions
      ansible.builtin.copy:
        src: files/unbound/unbound01.conf
        dest: /etc/unbound/unbound.conf.d/unbound01.conf
        owner: root
        group: root
        mode: '0644'
      notify: Restart unbound
      register: unbound01conf_file

    - name: Run CRON job to update root.hints every 3 months on the first day at 06:30.
      ansible.builtin.cron:
        name: "unbound update root.hints"
        month: "*/3"
        day: "01"
        hour: "06"
        minute: "00"
        job: "wget https://www.internic.net/domain/named.root -qO- | tee /var/lib/unbound/root.hints"

    - name: Restart unbound
      ansible.builtin.systemd_service:
        name: unbound
        state: restarted
      when: roothints_file.changed and unbound01conf_file.changed
