---
# file: inventory/host_vars/transmission01.yml
ansible_host: 192.168.1.31
node: pve01
vmid: 370
cores: 1
memory: 512
swap: 512
storage: local-lvm:2
mounts:
  mp0: /mnt/plex-media/torrents,mp=/mnt/data/torrents
mount_volumes: # on 9.2.0 - these fields are totally bugged, leaving this here for the time being til fix
  - id: mp0
    host_path: /mnt/plex-media/torrents
    mountpoint: /mnt/data/torrents
hwaddr: 02:00:00:00:00:1f
ip: 192.168.1.31/24
gw: 192.168.1.1
ip6: fe80::1f/11
gw6: fe80::ff:fe00:2201
features:
description: Transmission LXC - A Fast, Easy and Free Bittorrent Client
ostemplate: local:vztmpl/debian-12-standard_12.2-1_amd64.tar.zst
template_storage: local
template_content_type: vztmpl
template: debian-12-standard_12.2-1_amd64.tar.zst
notes: n/a
