---
# file: inventory/host_vars/pihole01.yml
ansible_host: 192.168.1.2
node: pve01
vmid: 100
cores: 1
memory: 128
swap: 256
storage: local-lvm
hwaddr: 02:00:00:00:00:02
ip: 192.168.1.2/24
gw: 192.168.1.1
ip6: fe80::2/10
gw6: fe80::ff:fe00:2201
features:
description: Pi-hole LXC - All DNS requests should be sent here
ostemplate: local:vztmpl/debian-12-standard_12.2-1_amd64.tar.zst
template_storage: local
template_content_type: vztmpl
template: debian-12-standard_12.2-1_amd64.tar.zst
notes: Needs a task to update sources and gravity
