---
# file: roles/proxmox_kvm_edit_container/tasks/main.yml
- name: Update config kvm vmid-{{ proxmox_kvm_edit_container_vmid }}
  community.general.proxmox_kvm:
    node: "{{ proxmox_kvm_edit_container_node }}"
    api_host: "{{ proxmox_kvm_edit_container_api_host }}"
    api_user: "{{ proxmox_kvm_edit_container_api_user }}"
    api_password: "{{ proxmox_kvm_edit_container_api_password }}"
    vmid: "{{ proxmox_kvm_edit_container_vmid }}"
    # TODO
    update: true
