---
# file: inventory/host_vars/plex01.yml
ansible_host: 192.168.1.25
node: pve01
vmid: 310
cores: 2
memory: 4096
swap: 4096
storage: local-lvm
mounts:
  mp0: /mnt/plex-media/plex,mp=/mnt/plex
hwaddr: 02:00:00:00:00:19
ip: 192.168.1.25/24
gw: 192.168.1.1
ip6: fe80::19/10
gw6: fe80::ff:fe00:2201
features:
description: Plex Media Server LXC - Transcode with hardware and USB storage
ostemplate: local:vztmpl/debian-12-standard_12.2-1_amd64.tar.zst
template_storage: local
template_content_type: vztmpl
template: debian-12-standard_12.2-1_amd64.tar.zst
notes: n/a
