---
# file: inventory/host_vars/plex01.yml
ansible_host: 192.168.1.12
vmid: 200
cores: 2
memory: 1024
storage: local-lvm
hwaddr: 02:00:00:00:00:0c
gw: 192.168.1.1
ip: 192.168.1.16/24
ip6: fe80::c
description: Plex Media Server LXC - Transcode with hardware and USB storage


# #     mounts: '{"mp0":"local:8,mp=/mnt/test/"}'
