---
# file: roles/lxc/tasks/main.yml
- name: Install Prometheus's node_exporter
  ansible.builtin.apt:
    name:
      - prometheus-node-exporter
    cache_valid_time: 3600

- name: Mask systemd-logind service due some internal errors is delaying ssh session login
  ansible.builtin.systemd_service:
    name: systemd-logind
    masked: true

# systemctl status systemd-logind.service
# systemctl mask systemd-logind.service
