---
# file: inventory/host_vars/docker01.yml
ansible_host: 192.168.1.14
ansible_user: debian
node: pve01
vmid: 220
cores: 1
memory: 2048
hwaddr: 02:00:00:00:00:0e
ip: 192.168.1.14/24
gw: 192.168.1.1
ip6: fe80::e/10
gw6: fe80::ff:fe00:2201
description: Docker KVM - Docker containers will be hosted here
notes: n/a
