---
# file: inventory/host_vars/bazarr01.yml
ansible_host: 192.168.1.33
node: pve01
vmid: 390
cores: 1
memory: 512
swap: 512
storage: local-lvm:4
mounts:
  mp0: /mnt/plex-media,mp=/mnt/data
mount_volumes: # on 9.2.0 - these fields are totally bugged, leaving this here for the time being til fix
  - id: mp0
    host_path: /mnt/plex-media
    mountpoint: /mnt/data
hwaddr: 02:00:00:00:00:21
ip: 192.168.1.33/24
gw: 192.168.1.1
ip6: fe80::21/91
gw6: fe80::ff:fe00:2201
features:
description: Bazarr LXC - Bazarr is a companion application to Sonarr and Radarr. It manages and downloads subtitles based on your requirements. You define your preferences by TV show or movie and Bazarr takes care of everything for you.
ostemplate: local:vztmpl/debian-12-standard_12.2-1_amd64.tar.zst
template_storage: local
template_content_type: vztmpl
template: debian-12-standard_12.2-1_amd64.tar.zst
notes: n/a
