groups:
- name: nodes
  rules:
  - alert: HostDown5
    expr: up{job="node_exporter"} == 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Host {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."

  - alert: HostDown10
    expr: up{job="node_exporter"} == 0
    for: 10m
    labels:
      severity: critical
    annotations:
      summary: "Host {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 10 minutes."

  - alert: HostMemory10
    expr: node_memory_MemAvailable_bytes{job="node_exporter"} / node_memory_MemTotal_bytes{job="node_exporter"} < 0.1
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Host {{ $labels.instance }} memory"
      description: "{{ $labels.instance }} of job {{ $labels.job }} with less than 10% free memory for more than 5 minutes."

  - alert: HostMemory20
    expr: node_memory_MemAvailable_bytes{job="node_exporter"} / node_memory_MemTotal_bytes{job="node_exporter"} < 0.2
    for: 30m
    labels:
      severity: warning
    annotations:
      summary: "Host {{ $labels.instance }} memory"
      description: "{{ $labels.instance }} of job {{ $labels.job }} with less than 20% free memory for more than 30 minutes."

  - alert: HostMemory30
    expr: node_memory_MemAvailable_bytes{job="node_exporter"} / node_memory_MemTotal_bytes{job="node_exporter"} < 0.3
    for: 24h
    labels:
      severity: info
    annotations:
      summary: "Host {{ $labels.instance }} memory"
      description: "{{ $labels.instance }} of job {{ $labels.job }} with less than 30% free memory for more than 24 hours."

  - alert: HostDisk10
    expr: node_filesystem_free_bytes{job="node_exporter"} / node_filesystem_size_bytes{job="node_exporter"} < 0.1
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Host {{ $labels.instance }} disk space"
      description: "{{ $labels.instance }} of job {{ $labels.job }} with less than 10% free disk space for more than 5 minutes."

  - alert: HostDisk20
    expr: node_filesystem_free_bytes{job="node_exporter"} / node_filesystem_size_bytes{job="node_exporter"} < 0.2
    for: 30m
    labels:
      severity: warning
    annotations:
      summary: "Host {{ $labels.instance }} disk space"
      description: "{{ $labels.instance }} of job {{ $labels.job }} with less than 20% free disk space for more than 30 minutes."

  - alert: HostDisk40
    expr: node_filesystem_free_bytes{job="node_exporter"} / node_filesystem_size_bytes{job="node_exporter"} < 0.4
    for: 24h
    labels:
      severity: info
    annotations:
      summary: "Host {{ $labels.instance }} disk space"
      description: "{{ $labels.instance }} of job {{ $labels.job }} with less than 40% free disk space for more than 24 hours."

  - alert: GrafanaDown5
    expr: up{job="grafana"} == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Grafana service {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."

  - alert: GraylogDown5
    expr: up{job="graylog"} == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Graylog service {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."

  # Alert for any instance that has a median request latency >1s.
  # - alert: APIHighRequestLatency
  #   expr: api_http_request_latencies_second{quantile="0.5"} > 1
  #   for: 10m
  #   annotations:
  #     summary: "High request latency on {{ $labels.instance }}"
  #     description: "{{ $labels.instance }} has a median request latency above 1s (current value: {{ $value }}s)"


# critical, error, warning, info
