---
# file: inventory/host_vars/unbound01.yml
ansible_host: 192.168.1.3
vmid: 110
cores: 1
memory: 256
storage: local-lvm
hwaddr: 02:00:00:00:00:03
gw: 192.168.1.1
ip: 192.168.1.3/24
ip6: fe80::3
description: Unbound LXC - All outbound DNS requests will pass through here
