---
# file: inventory/host_vars/unbound01.yml
ansible_host: 192.168.1.3
node: pve01
vmid: 110
cores: 1
memory: 128
storage: local-lvm
hwaddr: 03:00:00:00:00:03
ip: 192.168.1.3/24
gw: 192.168.1.1
ip6: fe80::3
gw6: fe80::ff:fe00:2201
description: Unbound LXC - All outbound DNS requests will pass through here
notes: Has a cron job every 3mon to udpate upstream regestries
