---
# file: inventory/host_vars/nzbget01.yml
ansible_host: 192.168.1.32
node: pve01
vmid: 380
cores: 1
memory: 256
swap: 256
storage: local-lvm:2
mounts:
  mp0: /mnt/plex-media/usenet,mp=/mnt/data/usenet
mount_volumes: # on 9.2.0 - these fields are totally bugged, leaving this here for the time being til fix
  - id: mp0
    host_path: /mnt/plex-media/usenet
    mountpoint: /mnt/data/usenet
hwaddr: 02:00:00:00:00:20
ip: 192.168.1.32/24
gw: 192.168.1.1
ip6: fe80::20/11
gw6: fe80::ff:fe00:2201
features:
description: NZBGet LXC - NZBGet is a binary downloader, which downloads files from Usenet based-on information given in nzb files.
ostemplate: local:vztmpl/debian-12-standard_12.2-1_amd64.tar.zst
template_storage: local
template_content_type: vztmpl
template: debian-12-standard_12.2-1_amd64.tar.zst
notes: n/a
