---
# file: roles/docker/tasks/main.yml

- name: Install aptitude
  ansible.builtin.apt:
    name: aptitude
    update_cache: true

- name: Install required system packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    update_cache: true

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/debian bookworm stable
    state: present

- name: Update apt and install docker-ce and docker-compose-plugin
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-compose-plugin
      - python3-docker
    update_cache: true
