---
# file: roles/proxmox_lxc_rm_container/tasks/main.yml

- name: Retrieve info lxc vmid-{{ proxmox_lxc_rm_container_vmid }}
  community.general.proxmox_vm_info:
    api_host: "{{ proxmox_lxc_rm_container_api_host }}"
    api_user: "{{ proxmox_lxc_rm_container_api_user }}"
    api_password: "{{ proxmox_lxc_rm_container_api_password }}"
    vmid: "{{ proxmox_lxc_rm_container_vmid }}"
  register:
    _proxmox_kvm_rm_container_vm_info

- name: Deletion block
  when: _proxmox_kvm_rm_container_vm_info.proxmox_vms | length
  block:
    - name: Stop with prejudice lxc vmid-{{ proxmox_lxc_rm_container_vmid }}
      community.general.proxmox:
        api_host: "{{ proxmox_lxc_rm_container_api_host }}"
        api_user: "{{ proxmox_lxc_rm_container_api_user }}"
        api_password: "{{ proxmox_lxc_rm_container_api_password }}"
        vmid: "{{ proxmox_lxc_rm_container_vmid }}"
        force: true
        state: stopped
    - name: Remove lxc vmid-{{ proxmox_lxc_rm_container_vmid }}
      community.general.proxmox:
        api_host: "{{ proxmox_lxc_rm_container_api_host }}"
        api_user: "{{ proxmox_lxc_rm_container_api_user }}"
        api_password: "{{ proxmox_lxc_rm_container_api_password }}"
        vmid: "{{ proxmox_lxc_rm_container_vmid }}"
        state: absent
