---
# file: roles/proxmox_kvm_rm_container/tasks/main.yml
- name: Stop container with prejudice
  community.general.proxmox_kvm:
    api_host: "{{ inventory_hostname }}"
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    vmid: "{{ hostvars[item].vmid }}"
    force: true
    state: stopped
  when: (hostvars[item].node == ansible_hostname) and (item in (ansible_limit | default(groups['kvm'])))
  loop: "{{ groups['kvm'] }}"

- name: Remove container
  community.general.proxmox_kvm:
    api_host: "{{ inventory_hostname }}"
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    vmid: "{{ hostvars[item].vmid }}"
    state: absent
  when: (hostvars[item].node == ansible_hostname) and (item in (ansible_limit | default(groups['kvm'])))
  loop: "{{ groups['kvm'] }}"
