---
# file: inventory/host_vars/logs01.yml
ansible_host: 192.168.1.13
node: pve01
vmid: 210
cores: 1
memory: 512
swap: 512
storage: local-lvm
hwaddr: 02:00:00:00:00:0d
ip: 192.168.1.13/24
gw: 192.168.1.1
ip6: fe80::d/10
gw6: fe80::ff:fe00:2201
features:
description: Docker LXC - All outbound DNS requests will pass through here
ostemplate: local:vztmpl/debian-12-standard_12.2-1_amd64.tar.zst
template_storage: local
template_content_type: vztmpl
template: debian-12-standard_12.2-1_amd64.tar.zst
notes: n/a
