---
# file: roles/proxmox_lxc_edit_container/tasks/main.yml
- name: Update config lxc vmid-{{ hostvars[item].vmid }}
  community.general.proxmox:
    node: "{{ proxmox_lxc_edit_container_node }}"
    api_host: "{{ proxmox_lxc_edit_container_api_host }}"
    api_user: "{{ proxmox_lxc_edit_container_api_user }}"
    api_password: "{{ proxmox_lxc_edit_container_api_password }}"
    vmid: "{{ proxmox_lxc_edit_container_vmid }}"
    hostname: "{{ proxmox_lxc_edit_container_hostname }}"
    cores: "{{ proxmox_lxc_edit_container_cores }}"
    memory: "{{ proxmox_lxc_edit_container_memory }}"
    swap: "{{ proxmox_lxc_edit_container_swap }}"
    storage: "{{ proxmox_lxc_edit_container_storage }}"
    netif:
      net0:
        name: "{{ proxmox_lxc_edit_container_netif_net0_name }}"
        hwaddr: "{{ proxmox_lxc_edit_container_netif_net0_hwaddr }}"
        ip: "{{ proxmox_lxc_edit_container_netif_net0_ip }}"
        gw: "{{ proxmox_lxc_edit_container_netif_net0_gw }}"
        ip6: "{{ proxmox_lxc_edit_container_netif_net0_ip6 }}"
        gw6: "{{ proxmox_lxc_edit_container_netif_net0_gw6 }}"
        bridge: "{{ proxmox_lxc_edit_container_netif_net0_bridge }}"
    pubkey: "{{ proxmox_lxc_edit_container_pubkey }}"
    timezone: "{{ proxmox_lxc_edit_container_timezone }}"
    description: "{{ proxmox_lxc_edit_container_description }}"
    onboot: "{{ proxmox_lxc_edit_container_onboot }}"
    update: true

# Stopped or mounted container can't be restarted
- name: Restart lxc vmid-{{ hostvars[item].vmid }}
  community.general.proxmox:
    api_host: "{{ proxmox_lxc_edit_container_api_host }}"
    api_user: "{{ proxmox_lxc_edit_container_api_user }}"
    api_password: "{{ proxmox_lxc_edit_container_api_password }}"
    vmid: "{{ proxmox_lxc_edit_container_vmid }}"
    state: restarted
