---
# file: roles/proxmox_lxc_edit_container/tasks/main.yml
- name: Update container configuration
  community.general.proxmox:
    node: "{{ hostvars[item].node }}"
    api_host: "{{ inventory_hostname }}"
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    vmid: "{{ hostvars[item].vmid }}"
    hostname: "{{ item }}"
    description: "{{ hostvars[item].description }}"
    cores: "{{ hostvars[item].cores }}"
    memory: "{{ hostvars[item].memory }}"
    swap: "{{ hostvars[item].swap }}"
    storage: "{{ hostvars[item].storage }}"
    netif: '{"net0":"name=eth0,hwaddr={{ hostvars[item].hwaddr }},gw={{ hostvars[item].gw }},ip={{ hostvars[item].ip }},gw6={{ hostvars[item].gw6 }},ip6={{ hostvars[item].ip6 }},bridge=vmbr0"}' # noqa: yaml[line-length]
    pubkey: "{{ lookup('ansible.builtin.file', 'ssh-keys/homelab.pub') }}"
    timezone: host
    onboot: true
    update: true
  when: (hostvars[item].node == ansible_hostname) and (item in (ansible_limit | default(groups['lxc'])))
  loop: "{{ groups['lxc'] }}"

- name: Restart container(stopped or mounted container you can't restart)
  community.general.proxmox:
    api_host: "{{ inventory_hostname }}"
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    vmid: "{{ hostvars[item].vmid }}"
    state: restarted
  when: (hostvars[item].node == ansible_hostname) and (item in (ansible_limit | default(groups['lxc'])))
  loop: "{{ groups['lxc'] }}"
