---
# file: roles/proxmox_lxc_add_container/tasks/main.yml
- name: Make sure base system container template is present
  community.general.proxmox_template:
    node: "{{ proxmox_lxc_add_container_node }}"
    api_host: "{{ proxmox_lxc_add_container_api_host }}"
    api_user: "{{ proxmox_lxc_add_container_api_user }}"
    api_password: "{{ proxmox_lxc_add_container_api_password }}"
    storage: "{{ proxmox_lxc_add_container_template_storage }}"
    content_type: "{{ proxmox_lxc_add_container_template_content_type }}"
    template: "{{ proxmox_lxc_add_container_template }}"
    state: present

- name: Add lxc vmid-{{ proxmox_lxc_add_container_vmid }}
  community.general.proxmox:
    node: "{{ proxmox_lxc_add_container_node }}"
    api_host: "{{ proxmox_lxc_add_container_api_host }}"
    api_user: "{{ proxmox_lxc_add_container_api_user }}"
    api_password: "{{ proxmox_lxc_add_container_api_password }}"
    vmid: "{{ proxmox_lxc_add_container_vmid }}"
    hostname: "{{ proxmox_lxc_add_container_hostname }}"
    cores: "{{ proxmox_lxc_add_container_cores }}"
    memory: "{{ proxmox_lxc_add_container_memory }}"
    swap: "{{ proxmox_lxc_add_container_swap }}"
    storage: "{{ proxmox_lxc_add_container_storage }}"
    netif:
      net0:
        name: "{{ proxmox_lxc_add_container_netif_net0_name }}"
        hwaddr: "{{ proxmox_lxc_add_container_netif_net0_hwaddr }}"
        ip: "{{ proxmox_lxc_add_container_netif_net0_ip }}"
        gw: "{{ proxmox_lxc_add_container_netif_net0_gw }}"
        ip6: "{{ proxmox_lxc_add_container_netif_net0_ip6 }}"
        gw6: "{{ proxmox_lxc_add_container_netif_net0_gw6 }}"
        bridge: "{{ proxmox_lxc_add_container_netif_net0_bridge }}"
    pubkey: "{{ proxmox_lxc_add_container_pubkey }}"
    ostemplate: "{{ proxmox_lxc_add_container_ostemplate }}"
    timezone: "{{ proxmox_lxc_add_container_timezone }}"
    description: "{{ proxmox_lxc_add_container_description }}"
    onboot: "{{ proxmox_lxc_add_container_onboot }}"
    state: present

- name: Start lxc vmid-{{ proxmox_lxc_add_container_vmid }}
  community.general.proxmox:
    api_host: "{{ proxmox_lxc_add_container_api_host }}"
    api_user: "{{ proxmox_lxc_add_container_api_user }}"
    api_password: "{{ proxmox_lxc_add_container_api_password }}"
    vmid: "{{ proxmox_lxc_add_container_vmid }}"
    state: started
